name: Release Module

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Read module version
      id: version
      run: |
        VERSION=$(node -p "require('./module.json').version")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Current version: $VERSION"
        
    - name: Check if release exists
      id: check_release
      run: |
        # Check if a release with this version already exists
        RELEASE_EXISTS=$(gh release list --limit 100 | grep -c "v${{ steps.version.outputs.version }}" || echo "0")
        echo "release_exists=$RELEASE_EXISTS" >> $GITHUB_OUTPUT
        
    - name: Create module.zip
      if: steps.check_release.outputs.release_exists == '0'
      run: |
        # Create zip file excluding .git and other unnecessary files
        zip -r module.zip . -x "*.git*" "*.github*" "node_modules/*" "*.DS_Store" "Thumbs.db"
        
    - name: Create Release
      if: steps.check_release.outputs.release_exists == '0'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: Release v${{ steps.version.outputs.version }}
        body: |
          ## Game Time Clock v${{ steps.version.outputs.version }}
          
          ### Changes
          - Automated release for version ${{ steps.version.outputs.version }}
          
          ### Installation
          Download the `module.zip` file and install it in your Foundry VTT modules directory.
        files: module.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Skip Release
      if: steps.check_release.outputs.release_exists == '1'
      run: |
        echo "Release v${{ steps.version.outputs.version }} already exists. Skipping release creation." 
